spring:
  datasource:
    url: jdbc:mysql://staging-db:3306/carizon
    username: carizon
    password: changeme
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            issuer-uri: https://accounts.google.com
carizon:
  redis:
    enabled: true
  rate-limit:
    enabled: true
