CREATE TABLE IF NOT EXISTS raw_listing (
  id VARCHAR(64) NOT NULL,
  source VARCHAR(32) NOT NULL,
  payload JSON NOT NULL,
  status ENUM(OK,CHANGED,REMOVED,ERROR) DEFAULT OK,
  scraped_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id, source)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
