version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: carizon-mysql
    environment:
      MYSQL_DATABASE: carizon
      MYSQL_USER: carizon
      MYSQL_PASSWORD: carizon!1
      MYSQL_ROOT_PASSWORD: root!1
      TZ: Asia/Seoul
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: carizon-redis
    environment:
      TZ: Asia/Seoul
    ports:
      - "6379:6379"
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: carizon-meilisearch
    environment:
      MEILI_ENV: development
      MEILI_NO_ANALYTICS: true
      TZ: Asia/Seoul
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    restart: unless-stopped

volumes:
  mysql_data:
  meili_data:
