version: "3.9"
services:
  meilisearch:
    image: getmeili/meilisearch:v1.11
    environment:
      - MEILI_ENV=development
      - MEILI_MASTER_KEY=masterKey
    ports:
      - "7700:7700"
    volumes:
      - meili:/meili_data

  cdn:
    image: nginx:alpine
    ports:
      - "8088:80"
    volumes:
      - ./cdn:/usr/share/nginx/html:ro
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  meili:
