server:
  port: 8080

spring:
  application:
    name: carizon-api
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/carizon?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: carizon
    password: carizon!1
    hikari:
      maximum-pool-size: 10
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 100
  
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
  
  jackson:
    time-zone: Asia/Seoul
    serialization:
      write-dates-as-timestamps: false
  
  cache:
    type: redis
  
  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    root: INFO
    org.springframework.jdbc: DEBUG
    org.mybatis: DEBUG
    com.zaxxer.hikari: INFO
    com.carizon: DEBUG
    org.flywaydb: INFO

---
# Dev profile
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

---
# Test profile
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/carizon_test?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: test
    password: test