server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/carizon?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: carizon
    password: carizon!1
  jackson:
    time-zone: Asia/Seoul

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.jdbc: DEBUG
    org.mybatis: DEBUG
    com.zaxxer.hikari: DEBUG
    com.carizon: DEBUG