name: Deploy Frontend
on:
  push:
    branches: [ main ]
    paths: [ "frontend/**", ".github/workflows/deploy-frontend.yml", "infra/**" ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - name: Build
        working-directory: frontend
        run: |
          npm ci
          npm run build
      - name: Build & Push Docker (GHCR)
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
          IMAGE=ghcr.io/${{ secrets.GHCR_USERNAME }}/carizon-frontend
          TAG=main-${{ github.sha }}
          docker build -t $IMAGE:$TAG -t $IMAGE:latest frontend
          docker push $IMAGE:$TAG
          docker push $IMAGE:latest
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e
            cd /opt/app
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            sed -i "s/REPLACE_GH_USER/${{ secrets.GHCR_USERNAME }}/g" infra/docker-compose.yml
            docker compose -f infra/docker-compose.yml pull frontend caddy || true
            docker compose -f infra/docker-compose.yml up -d --remove-orphans
